### ISSUE TITLE
Error: Cannot find module '/home/jeff/solid/solid-rest/core/'

### ISSUE THREAD

**Issue by jaxoncreed** [solid/solid-rest#76]
I think the most recent version of solid-rest had a build problem committed to NPM. Running the code gives me this error:

```
Error: Cannot find module '/home/jeff/solid/solid-rest/core/'
Require stack:
- /Users/jackson/O/clone-to-solid-pod/node_modules/@solid-rest/file/dist/cjs/index.js
- /Users/jackson/O/clone-to-solid-pod/node_modules/solid-node-client/dist/cjs/index.js
- /Users/jackson/O/clone-to-solid-pod/lib/index.ts
```

The file at `/node_modules/@solid-rest/file/dist/cjs/index.js` has this line:

```
var _core = _interopRequireDefault(require("/home/jeff/solid/solid-rest/core/"));
```

**Comment by jeff-zucker** [comment]
Did you build the new version 2.1.8 of @solid-rest/file?  I just built it and grepped for "/home/jeff/solid" and found nothing in the dist/cjs/index.js or any other file.  The previous version did have a mistaken reference to a local file in the src/index.js but I fixed that when I fixed the $rdf thing so my guess is that you are looking at something built with the previous version.  I'm up so if this turns out not to be the case, ping me.

**Comment by jaxoncreed** [comment]
I'm just installing it from npm. I see that there is no reference to /home/jeff/solid in the codebase, but when I install from npm, it's there. Do you see that too?

**Comment by jeff-zucker** [comment]
Nuts, yeah, I just pulled from npm and the grep turned it up.  So I just uploaded 2.1.9, sorry for the problems.

**Comment by jaxoncreed** [comment]
Thanks, could you also release a new version of solid-node-client that uses v2.1.9 of @solid-rest?

**Comment by jeff-zucker** [comment]
I just npm'd v.2.1.2 of solid-node-client which requires v2.1.9 of @solid-rest/file.

**Comment by jeff-zucker** [comment]
P.S. If you want faster response time, ping me in chat :-)
